spring:
  # 空间图片分表
  shardingsphere:
    datasource:
      names: shared_picture_platform
      shared_picture_platform:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shared_picture_platform
        username: root
        password: 88888888
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: shared_picture_platform.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.chen.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true
  session:
    store-type: redis
    timeout: 2592000
  application:
    name: shared-picture-platform
    # Redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    password: 1234
    port: 6379
    timeout: 5000
    username: default
  # 运行环境
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
server:
  # 端口号
  port: 8123
  servlet:
    # 根路径
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    # 取消驼峰命名映射
    map-underscore-to-camel-case: false
    # 开启日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      logic-delete-field: isDelete # 删除字段
      logic-delete-value: 1 # 删除值
      logic-not-delete-value: 0 # 未删除值

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.chen.controller
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000